name: Python 3.10

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python 3.10.3
      run: |
        sudo apt update
        sudo apt install python3.10
        
    - name: Install dependencies
      run: |
        make install
        pip install -r requirements.txt

    - name: Lint with Pylint
      run: |
        make lint

    - name: Test with Pytest
      run: |
        make test
