name: Python 3.10

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.3

    - name: Install dependencies
      run: |
        make install
        pip install -r requirements.txt

    - name: Lint with Pylint
      run: |
        make lint

    - name: Test with Pytest
      run: |
        make test
